spring:
  application:
    name: santander-dev-week-24
  datasource:
    url: jdbc:h2:mem:sdw24
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

openai:
  base-url: https://api.openai.com
  api-key: ${OPENAI_API_KEY}

gemini:
  base-url:
  api-key: ${GEMINI_API_KEY}